### ISSUE TITLE
feature: Deploy multiple resources patch-baseline's and maintenance window 's  

### ISSUE THREAD

**Issue by choudharyac09** [cloudposse/terraform-aws-ssm-patch-manager#16]
Have a question? Please check out our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Feature to add multiple patch baseline 
Feature to create multiple maintenance windows and task 

## Expected Behavior

The Expected behaviour of this would be to deploy baseline for multiple types of Os versions and have multiple maintenances windows such that one could have different patching schedules in the same account for various types of os at different schedules. 

## Use Case

This feature request is related to a problem where one could have multiple EC2 Instances in the same account with different OS versions (RedHat and window) and different patching schedules. 

##  Ideal Solution

Deploy multiple resources with for_each

**Comment by Gowiem** [comment]
@choudharyac09 happy to discuss this issue further if you still need this, but what I would suggest doing here is to deploy multiple versions of the `ssm-patch-manager` module and configure each for the OS / windows that you need in your root module. Then you can determine the number of patch-managers that you require and we don't need to make this child module more complex since that is not a common use-case. 

Please reopen if you feel there is still a direct need for this that you want to see addressed!
